### ISSUE TITLE
Rubio has dropped out of the race; Should remove reference to avoid looking out-of-touch.

### ISSUE THREAD

**Issue by Blendrix** [jacobnisnevich/i-like-bernie-but#18]
Issue exists under the #is-he-electable? heading. 

The answer says:
"Bernie performs better than Hillary does in all hypothetical match-ups against Republicans in poll after poll (2.4% better against Trump, 4.6% better against Cruz, and 1.5% better against Rubio, on average)."

Rubio dropped out of the race already, so how Bernie polls against him is irrelevant at this point. We should focus on how he polls against the Republican candidates that are still in the running: Trump, Cruz, and Kasich.

**Comment by AlexNisnevich** [comment]
Thanks for bringing this to our attention!
