### ISSUE TITLE
Licensing?

### ISSUE THREAD

**Issue by ghost** [jacobnisnevich/i-like-bernie-but#19]
Hello from [CodersForJill](https://jillstein.herokuapp.com/)!

We're looking into repurposing some of the awesome infrastructure built for the Bernie campaign. Would you be open to licensing this project under MIT or similar?

Thanks!

**Comment by jacobnisnevich** [comment]
Sure! Feel free to re-use any and all of the code @AlexNisnevich and I used to make this site. I went ahead and added an MIT license to the repository too. Let me know if you guys need any help with making I Like Jill, But...
