### ISSUE TITLE
Use hash values to point directly to specific Q&A

### ISSUE THREAD

**Issue by jlegrone** [jacobnisnevich/i-like-bernie-but#2]

**Comment by itzsaga** [comment]
I'm wondering why you think this is needed? The current implementation looks to be working fine.

**Comment by edg2s** [comment]
A hash would allow you to share links to a specific question

**Comment by jlegrone** [comment]
What @edg2s said; this is an enhancement. Allowing people to share specific Q&As is a use case that might be worth supporting.

**Comment by jacobnisnevich** [comment]
Done!
