### ISSUE TITLE
Bottom of TOC is hidden

### ISSUE THREAD

**Issue by itzsaga** [jacobnisnevich/i-like-bernie-but#3]
With a 3200 x 1800 resolution in Chrome the last 3 questions are below the fold in the TOC.

**Comment by AlexNisnevich** [comment]
Agreed that this is an issue but not sure what the best solution would be. What do you think?

**Comment by itzsaga** [comment]
I didn't look before posting the issue. The current pull request should fix this.

**Comment by jlegrone** [comment]
Yep, current [PR](https://github.com/jacobnisnevich/i-like-bernie-but/pull/1) brings the sidebar to the top of the screen as you scroll down from the top of the page. There's still the issue of insufficient vertical space if more questions are added or the device height is small.

I would suggest making the sidebar a true fixed sidebar to the left of the content, which scrolls with overflow. This is more of a design decision though so I left unimplemented.

**Comment by AlexNisnevich** [comment]
Should be fixed now.
